DROP TABLE IF EXISTS INVENTORY;

CREATE TABLE INVENTORY
(
    ARTICLE_ID NUMBER PRIMARY KEY,
    ARTICLE_NAME VARCHAR ,
    STOCK NUMBER
);

DROP TABLE IF EXISTS PRODUCT;

CREATE TABLE PRODUCT
(
    PRODUCT_NAME VARCHAR PRIMARY KEY,
    PRODUCT_PRICE NUMBER(10,2)
);

DROP TABLE IF EXISTS BILL_OF_MATERIAL;

CREATE TABLE BILL_OF_MATERIAL
(
    BOM_ID NUMBER PRIMARY KEY,
    PRODUCT_NAME VARCHAR,
    ARTICLE_ID NUMBER ,
    AMOUNT_OF NUMBER
);
